### ISSUE TITLE
some error happed when I install dependencies

### ISSUE THREAD

**Issue by zidoshare** [LekoArts/gatsby-starter-portfolio-cara#12]
The verbose log:
```
verbose 8.997 Error: /home/zido/front/resume/node_modules/sharp: Command failed.
Exit code: 127
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/zido/front/resume/node_modules/sharp
Output:
info sharp Using cached /home/zido/.npm/_libvips/libvips-8.7.0-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=11.3.0 runtime=node arch=x64 platform=linux)
/bin/sh: node-gyp: command not found
    at ProcessTermError.ExtendableBuiltin (/usr/lib/node_modules/yarn/lib/cli.js:727:66)
    at ProcessTermError.MessageError (/usr/lib/node_modules/yarn/lib/cli.js:756:123)
    at new ProcessTermError (/usr/lib/node_modules/yarn/lib/cli.js:796:113)
    at ChildProcess.<anonymous> (/usr/lib/node_modules/yarn/lib/cli.js:25795:17)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
error /home/zido/front/resume/node_modules/sharp: Command failed.
Exit code: 127
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments: 
Directory: /home/zido/front/resume/node_modules/sharp
Output:
info sharp Using cached /home/zido/.npm/_libvips/libvips-8.7.0-linux-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=11.3.0 runtime=

```

How to fix it ? Thanks

**Comment by zidoshare** [comment]
OS:  Linux(archlinux)
node: v11.3.0
yarn: 1.12.3

**Comment by zidoshare** [comment]
sorry,I fixed it.

I try to switch node version to v10.14.1.
